from datetime import datetime
from database.database import db


class MitigationRequest(db.Model):
    """Persists defensive mitigation proposals generated by Person 4 and admin approvals.

    Ensures safe lab execution by requiring explicit administrator approval
    before transitioning from PENDING to APPROVED to EXECUTED.
    """
    __tablename__ = "mitigation_requests"

    id = db.Column(db.Integer, primary_key=True)

    request_code = db.Column(db.String(32), nullable=False, unique=True, index=True)
    incident_id = db.Column(
        db.Integer, db.ForeignKey("incidents.id", ondelete="SET NULL"), nullable=True, index=True
    )

    action_type = db.Column(db.String(50), nullable=False)  # ISOLATE_DEVICE, STATIC_ARP_ENTRY, etc.
    target_mac = db.Column(db.String(17), nullable=False, index=True)
    target_ip = db.Column(db.String(45), nullable=True)
    reason = db.Column(db.Text, nullable=False)

    # Lifecycle status: PENDING -> APPROVED / REJECTED -> EXECUTED / FAILED
    status = db.Column(db.String(20), nullable=False, default="PENDING", index=True)
    approved_by = db.Column(db.String(50), nullable=True)
    execution_result = db.Column(db.Text, nullable=True)

    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow, index=True)
    executed_at = db.Column(db.DateTime, nullable=True)

    # Relationships
    recovery_logs = db.relationship(
        "RecoveryLog", backref="mitigation_request", lazy="select", cascade="all, delete-orphan"
    )

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "request_code": self.request_code,
            "incident_id": self.incident_id,
            "action_type": self.action_type,
            "target_mac": self.target_mac,
            "target_ip": self.target_ip,
            "reason": self.reason,
            "status": self.status,
            "approved_by": self.approved_by,
            "execution_result": self.execution_result,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
        }